version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/despacho_legal
    # depends_on:
    #   - db
  frontend:
    build: ./frontendexit
    ports:
      - "5173:80"
    depends_on:
      - backend
  chatbot:
    build: ./chatbot
    ports:
      - "5000:5000"
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: despacho_legal
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata: 