[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/deployment/Dockerfile"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production" 