services:
  # Backend API Service
  - type: web
    name: experimento2-backend
    env: node
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: experimento2-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    healthCheckPath: /api/health

  # Frontend Web Service
  - type: web
    name: experimento2-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://experimento2-backend.onrender.com
      - key: VITE_CHATBOT_URL
        value: https://experimento2-chatbot.onrender.com
      - key: VITE_ENV
        value: production

  # Chatbot Service
  - type: web
    name: experimento2-chatbot
    env: python
    buildCommand: cd chatbot && pip install -r requirements.txt
    startCommand: cd chatbot && python main_improved_fixed.py
    envVars:
      - key: BACKEND_URL
        value: https://experimento2-backend.onrender.com
      - key: PORT
        value: 8000

databases:
  - name: experimento2-db
    databaseName: experimento2
    user: experimento2_user 